

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: eventpw

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    #show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #format_sql: true
        jdbc:
          # batch_size: 5
  flyway:
    baselineOnMigrate: true

server:
  port: 8092

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO